apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30060
      protocol: TCP
      name: http
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
